language: php

dist: trusty
sudo: false

branches:
  only:
    - master

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache
    - vendor/

before_install:
  - composer selfupdate

install: composer update --prefer-source --no-interaction --optimize-autoloader

script: vendor/bin/phpunit --configuration phpunit.xml